
'use client';

import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis } from 'recharts'
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "@/components/ui/table"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { DollarSign, Package, CreditCard, Users } from "lucide-react"
import Link from 'next/link';

const chartData = [
    { month: "Jan", revenue: 1200 },
    { month: "Feb", revenue: 1800 },
    { month: "Mar", revenue: 1500 },
    { month: "Apr", revenue: 2200 },
    { month: "May", revenue: 2500 },
    { month: "Jun", revenue: 3100 },
]

const recentReferrals = [
    { id: 'usr_1', date: '2024-07-15', commission: '₹50' },
    { id: 'usr_2', date: '2024-07-14', commission: '₹25' },
    { id: 'usr_3', date: '2024-07-12', commission: '₹100' },
    { id: 'usr_4', date: '2024-07-11', commission: '₹50' },
]

export default function PartnerDashboard() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6 justify-between">
            <h1 className="text-xl font-semibold">Partner Dashboard</h1>
            <div className="flex items-center gap-4">
                 <Link href="/partner" className='text-sm text-muted-foreground hover:text-primary'>
                    Partner Program Home
                </Link>
                 <Button variant="outline" size="sm" asChild>
                     <Link href="/">1ShopApp Home</Link>
                </Button>
                 <Avatar>
                    <AvatarImage src="https://picsum.photos/seed/partner/100/100" alt="Partner" />
                    <AvatarFallback>P</AvatarFallback>
                </Avatar>
            </div>
        </header>
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
        <div className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                Total Revenue Generated
              </CardTitle>
              <DollarSign className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₹45,231.89</div>
              <p className="text-xs text-muted-foreground">
                All-time revenue from your referrals
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                Total Commission Earned
              </CardTitle>
              <CreditCard className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₹4,523.18</div>
              <p className="text-xs text-muted-foreground">
                10% of total revenue
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Referrals</CardTitle>
              <Users className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">+235</div>
              <p className="text-xs text-muted-foreground">
                +32 in the last month
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Your Referral Code</CardTitle>
              <Package className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">RAJU-MOBILES</div>
               <p className="text-xs text-muted-foreground">
                Share this code with your customers
              </p>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4 md:gap-8 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Monthly Revenue</CardTitle>
              <CardDescription>
                Revenue generated by your referrals over the last 6 months.
              </CardDescription>
            </CardHeader>
            <CardContent className="pl-2">
              <ResponsiveContainer width="100%" height={350}>
                <BarChart data={chartData}>
                  <XAxis
                    dataKey="month"
                    stroke="#888888"
                    fontSize={12}
                    tickLine={false}
                    axisLine={false}
                  />
                  <YAxis
                    stroke="#888888"
                    fontSize={12}
                    tickLine={false}
                    axisLine={false}
                    tickFormatter={(value) => `₹${value / 1000}K`}
                  />
                  <Bar dataKey="revenue" fill="currentColor" radius={[4, 4, 0, 0]} className="fill-primary" />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
          <Card className="flex flex-col">
            <CardHeader>
              <CardTitle>Recent Referrals</CardTitle>
              <CardDescription>
                Users who signed up using your referral code.
              </CardDescription>
            </CardHeader>
            <CardContent className='flex-grow'>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>User ID</TableHead>
                            <TableHead>Date</TableHead>
                            <TableHead className='text-right'>Commission</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {recentReferrals.map((referral) => (
                             <TableRow key={referral.id}>
                                <TableCell className='font-medium'>{referral.id}</TableCell>
                                <TableCell>{referral.date}</TableCell>
                                <TableCell className='text-right'>{referral.commission}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
